// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorCycle.Data.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotorCycle.Data.Migrations
{
    [DbContext(typeof(MotoContext))]
    [Migration("20240510034427_Change_Table_Locacao_To_Rental")]
    partial class Change_Table_Locacao_To_Rental
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Motorcycle.Domain.Models.DeliveryDriver", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Identificador"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagemCNH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCNH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoCNH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Identificador");

                    b.ToTable("DeliveryDriver", (string)null);
                });

            modelBuilder.Entity("Motorcycle.Domain.Models.Locacao", b =>
                {
                    b.Property<int>("IdLocacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdLocacao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLocacao"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataFim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInicio");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("IdCliente");

                    b.Property<int>("IdMotocicleta")
                        .HasColumnType("integer")
                        .HasColumnName("IdMotocicleta");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Observacoes");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric")
                        .HasColumnName("Preco");

                    b.HasKey("IdLocacao");

                    b.ToTable("Locacao", (string)null);
                });

            modelBuilder.Entity("Motorcycle.Domain.Models.Moto", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Identificador"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("ClassLevelCascadeMode")
                        .HasColumnType("integer");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RuleLevelCascadeMode")
                        .HasColumnType("integer");

                    b.HasKey("Identificador");

                    b.ToTable("Moto", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
